version: "3.9"

services:
  controller:
    build: ./controller/
  documentanalyzer:
    build:
  queryrunner:
    build:
  resultstorage:
    build:
  tasktracker:
    build:
  usermanager:
    build:
  broker:
    image: rabbitmq:3.10.5
    hostname: broker
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  db:
    image: postgres:14.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPASSWORD=postgres
  s3:
    image: minio/minio:RELEASE.2020-10-28T08-16-50Z
    hostname: s3
    restart: unless-stopped
    command: server /data
    ports:
      - "9000:9000"
    expose:
      - 9000
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - MINIO_REGION_NAME=my_region
    volumes:
      - /mnt/data:/data